# Makefile

REMOTE='root@s1'
WORKDIR='/tmp/nc'
TARNAME='nc-pre-gen.tgz'

gen:
	rm -rf build/ext build/nc
	tar czf build/$(TARNAME) config.json nc
	ssh $(REMOTE) "rm -rf $(WORKDIR) && mkdir -p $(WORKDIR)"
	scp build/$(TARNAME) $(REMOTE):$(WORKDIR)/
	ssh $(REMOTE) "cd $(WORKDIR) && tar xzf $(TARNAME) && zephir generate && tar czf ext.tgz ext"
	scp $(REMOTE):$(WORKDIR)/ext.tgz build/
	tar xzf build/ext.tgz -C build/
	sed -i 's# /Oi /Ot /Oy /Ob2 /Gs /GF /Gy /GL##g' build/ext/config.w32
	sed -i '/\/LTCG/d' build/ext/config.w32
	mv build/ext build/nc
