
extern zend_class_entry *nc_storage_namepolicy_storagenamepolicyawareinterface_ce;

ZEPHIR_INIT_CLASS(Nc_Storage_NamePolicy_StorageNamePolicyAwareInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_nc_storage_namepolicy_storagenamepolicyawareinterface_setstoragenamepolicy, 0, 0, 1)
	ZEND_ARG_OBJ_INFO(0, storageNamePolicy, Nc\\Storage\\NamePolicy\\StorageNamePolicyInterface, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(nc_storage_namepolicy_storagenamepolicyawareinterface_method_entry) {
	PHP_ABSTRACT_ME(Nc_Storage_NamePolicy_StorageNamePolicyAwareInterface, setStorageNamePolicy, arginfo_nc_storage_namepolicy_storagenamepolicyawareinterface_setstoragenamepolicy)
	PHP_ABSTRACT_ME(Nc_Storage_NamePolicy_StorageNamePolicyAwareInterface, getStorageNamePolicy, NULL)
  PHP_FE_END
};
