
extern zend_class_entry *nc_storage_backend_storagebackendawareinterface_ce;

ZEPHIR_INIT_CLASS(Nc_Storage_Backend_StorageBackendAwareInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_nc_storage_backend_storagebackendawareinterface_setstoragebackend, 0, 0, 1)
	ZEND_ARG_OBJ_INFO(0, storageBackend, Nc\\Storage\\Backend\\StorageBackendInterface, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(nc_storage_backend_storagebackendawareinterface_method_entry) {
	PHP_ABSTRACT_ME(Nc_Storage_Backend_StorageBackendAwareInterface, setStorageBackend, arginfo_nc_storage_backend_storagebackendawareinterface_setstoragebackend)
	PHP_ABSTRACT_ME(Nc_Storage_Backend_StorageBackendAwareInterface, getStorageBackend, NULL)
  PHP_FE_END
};
